name: 自动访问程序

on:
  workflow_dispatch:
  schedule:
    - cron: "*/40 * * * *"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests chardet
      - name: Execute Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          WEB_URL: ${{ secrets.WEB_URL }}
        run: |
          python main.py
